---

- name: Update all packages on a Debian/Ubuntu & autoremove
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists
  
- name: Wait for system to become reachable again
  wait_for_connection:
    delay: 10
    timeout: 300