- name: Install Roles
  gather_facts: yes
  hosts: all
  connection: ssh
  become: True
  roles:
  - { role: weareinteractive.users }
  - { role: geerlingguy.pip }
  - { role: geerlingguy.ntp }
  - { role: security }
  - { role: docker }
  - { role: os }
  - { role: akin_ozer.ansible_role_ssl, server_hostname: devop.com }
  - { role: mythic-c2-docker, server_hostname: devop.com }